// Automatically generated by SUtools, editing not advised.
#ifndef R_PLIABLE_H
#define R_PLIABLE_H
#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>
#ifdef ENABLE_NLS
#include <libintl.h>
#define _(String) dgettext ("pliable", String)
#else
#define _(String) (String)
#endif

#define FDEF(name)  {#name, (DL_FUNC) &F77_SUB(name), sizeof(name ## _t)/sizeof(name ## _t[0]), name ##_t}
void F77_SUB(pliable)(
int *no,
int *ni,
int *nz,
double *x,
double *y,
double *w,
double *alpha,
int *nlam,
double *ulam,
int *kbos,
int *maxinter,
int *linenter,
double *thr,
double *pf,
int *maxit,
double *tbk,
int *mxthit,
int *mxkbt,
int *mxth,
int *kpmx,
int *kthmx,
int *mlam,
double *a0,
int *lp,
int *istor,
double *fstor,
double *thstor,
int *jerr
);
 
static R_NativePrimitiveArgType pliable_t[] = {
INTSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP,
INTSXP,
INTSXP,
INTSXP,
REALSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP
};
void F77_SUB(modstor)(
int *iv,
double *av,
int *noth,
int *nz,
double *thv,
int *kpmx,
int *kthmx,
int *istor,
double *fstor,
double *thstor,
int *kp,
int *kth,
int *jerr
);
 
static R_NativePrimitiveArgType modstor_t[] = {
INTSXP,
REALSXP,
INTSXP,
INTSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP
};
void F77_SUB(modpred)(
int *no,
int *ni,
int *nz,
double *x,
double *a0,
int *kpl,
int *istor,
double *fstor,
double *thstor,
double *fh
);
 
static R_NativePrimitiveArgType modpred_t[] = {
INTSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(modsoln)(
int *nz,
int *kpl,
int *istor,
double *fstor,
double *thstor,
int *kv,
int *iv,
double *av,
int *it,
int *kz,
double *tv
);
 
static R_NativePrimitiveArgType modsoln_t[] = {
INTSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
REALSXP,
INTSXP,
INTSXP,
REALSXP
};


#define FDEF(name)  {#name, (DL_FUNC) &F77_SUB(name), sizeof(name ## _t)/sizeof(name ## _t[0]), name ##_t}
void F77_SUB(logpliable)(
int *no,
int *ni,
int *nz,
double *x,
double *y,
double *w,
double *alpha,
int *nlam,
double *ulam,
int *kbos,
int *maxinter,
int *linenter,
double *thr,
double *pf,
int *maxit,
double *tbk,
int *mxthit,
int *mxkbt,
int *mxth,
int *kpmx,
int *kthmx,
int *mlam,
double *a0,
int *lp,
int *istor,
double *fstor,
double *thstor,
int *jerr
);
 
static R_NativePrimitiveArgType logpliable_t[] = {
INTSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP,
INTSXP,
INTSXP,
INTSXP,
REALSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP
};


static R_FortranMethodDef fMethods[] = {
FDEF(pliable) ,
FDEF(modstor) ,
FDEF(modpred) ,
FDEF(modsoln) ,
FDEF(logpliable) ,
{NULL, NULL, 0}
};

void R_init_pliable(DllInfo *dll){
  R_registerRoutines(dll, NULL, NULL, fMethods, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
#endif
